

services:
  db:
    image: postgres:15
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:db_password
      POSTGRES_DB:db_name
    ports:
      - "5432:5432"#db default port
    volumes:
      - pgdata:/var/lib/postgresql/data

  web_app:
    build: .
    container_name: ecommerce_dashboard
    restart: always
    ports:
      - "8501:8501"#streamlit default port
    environment:
      - DB_HOST=db
      - DB_NAME=db_name
      - DB_PASSWORD=db-password
    depends_on:
      - db

volumes:
  pgdata: